NAME=PetShop

CC=g++ -std=c++17
FLAGS=-Wall -Wextra -Werror
SRC=Application.cpp
RM =rm -rf

all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(FLAGS) $(LIBS) $(SRC) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

run: re
	./$(NAME)

debug: fclean
	$(CC) $(FLAGS) $(SRC) -o $(NAME)
